move_group:
  ros__parameters:
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

    moveit_simple_controller_manager:
      controller_names:
        - joint_trajectory_controller
        - gripper_controller

      joint_trajectory_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: true
        joints:
          - base_link_Revolute-1
          - link1_Revolute-3
          - link2_Revolute-4
          - link3_Revolute-5
          - link4_Revolute-6
          - link5_Revolute-7

      gripper_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: false
        joints:
          - link6_Slider-8