arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
  kinematics_solver_attempts: 10

gripper:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 5  # Reduced for single-joint efficiency
  # root_name: link5  # Matches SRDF base (uncomment if needed for custom chain)
  # tip_names:  # Array of tips (uncomment and adjust if your gripper has multiple tips)
  #  - gripper_ee