moveit_simple_controller_manager:
  controller_names:
    - arm_controller
  arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - base_link_Revolute-1
      - link1_Revolute-3
      - link2_Revolute-4
      - link3_Revolute-5
      - link4_Revolute-6
      - link5_Revolute-7
  gripper_controller:
    action_ns: gripper_cmd  # If separate; adjust if your gripper uses a different action
    type: GripperCommand
    default: true
    joints:
      - link6_Slider-8