planning_provider: ompl_interface/OMPLPlanner

ompl:
  ros__parameters:
    planning_plugins:
      - ompl_interface/OMPLPlanner
    request_adapters: >-
      default_planner_request_adapters/AddTimeOptimalParameterization
      default_planner_request_adapters/FixWorkspaceBounds
      default_planner_request_adapters/FixStartStateBounds
      default_planner_request_adapters/FixStartStateCollision
      default_planner_request_adapters/FixStartStatePathConstraints

    # Set the resampling time step to fix execution errors
    add_time_optimal_parameterization:
      resample_dt: 0.05
    
    # Define the default planners for the 'arm' group
    arm:
      planner_configs:
        - RRTConnect
      projection_evaluator: joints(link1_Revolute-3,link2_Revolute-4)
      longest_valid_segment_fraction: 0.005