planner_configs:
  - SBLkConfigDefault
  - ESTkConfigDefault
  - LBKPIECEkConfigDefault
  - BKPIECEkConfigDefault
  - KPIECEkConfigDefault
  - RRTkConfigDefault
  - RRTConnectkConfigDefault
  - RRTstarkConfigDefault
  - TRRTkConfigDefault
  - PRMkConfigDefault
  - PRMstarkConfigDefault

arm:  # Your planning group
  planner_configs: [RRTConnectkConfigDefault]  # Fast and reliable for prismatic
  projection_evaluator: joints(base_link_Revolute-1, link1_Revolute-3)  # Tweak if needed for your arm
  longest_valid_segment_fraction: 0.005