controller_manager:
  ros__parameters:
    update_rate: 100  # Hz (matches your hardware)

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/GripperActionController  # For position cmds on prismatic

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_link_Revolute-1
      - link1_Revolute-3
      - link2_Revolute-4
      - link3_Revolute-5
      - link4_Revolute-6
      - link5_Revolute-7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      # No effort—your hardware doesn't export it

    # Optional: From OpenArm—tolerances for smoother exec
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.1  # Min 0.1s duration (fixes zero-time shorts)

gripper_controller:
  ros__parameters:
    joint: link6_Slider-8
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity