# config/servo.yaml
moveit_servo:
  ros__parameters:
    robot_link_command_frame: "gripper"  # Your EEF (refutes 'gripper_ee' default—tools: Match URDF exactly; if gripper tip is 'gripper', use that—check xacro: ls config/MarkII_urdf.urdf.xacro, grep for end-effector)
    ee_frame_name: "gripper"
    # Adjust "arm" if your planning group in SRDF is different
    move_group_name: "arm"
    planning_frame: "base_link"  # From your URDF
    command_in_type: "unitless"  # Joystick inputs are scaled [0-1], treat as fractions of max speed
    scale:
      linear: 0.1  # Max linear speed (m/s) - tune low for safety
      rotational: 0.5  # Max angular speed (rad/s) - tune for your arm
    publish_period: 0.02  # 50Hz updates for responsiveness
    collision_check_type: false  # Stop if collision detected
    command_out_type: "trajectory_msgs/JointTrajectory"
    joint_topic: "/joint_states"  # Your node already publishes this
    outgoing_command_topic: "/arm_controller/joint_trajectory"  # Custom topic for bridge
    cartesian_command_in_topic: "/servo_node/delta_twist_stamped_cmds"